import type { Metadata } from "next";
import { FaGlobeEurope } from "react-icons/fa";
import Image from "next/image";
import Logo from '../public/home/logo.png'
import { FaFacebook } from "react-icons/fa";
import { FaTwitter } from "react-icons/fa";
import { FaLinkedin } from "react-icons/fa";
import { FaPhoneAlt } from "react-icons/fa";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>


                <header className="w-full flex justify-between px-10 bg-primary">
                    <div className="flex">
                        <div className="flex px-1 py-2 mx-1 items-center">
                            <FaPhoneAlt />
                            <p className="text-whtie items-center ps-1">
                                923362164294
                            </p>
                        </div>
                        <div className="flex px-1 py-2 mx-1 items-center">
                            <FaPhoneAlt />
                            <p className="text-whtie ps-1">
                                923362164294
                            </p>
                        </div>
                    </div>


                    <div className="flex">
                        <div className="flex py-2 items-center">
                            <p className="mx-2">
                                About Us
                            </p>
                            <p className="mx-2">
                                Blogs
                            </p>

                            <p className="mx-2">
                                Gallery
                            </p>
                            <p className="mx-2">
                                Brouchers
                            </p>

                        </div>
                        <div className="flex py-2 items-center bg-[#FBAD17] mx-3 px-4 ">
                            <FaFacebook className="text-xl text-white mx-2" />
                            <FaTwitter className="text-xl text-white mx-2" />
                            <FaLinkedin className="text-xl text-white mx-2" />
                        </div>

                        <div className="flex py-2 ms-8">

                            <p className="mx-1">
                                User login
                            </p>
                            <p>
                                |
                            </p>
                            <p className="mx-1">
                                Agent login
                            </p>

                        </div>

                    </div>
                </header>

                <header className="w-full flex justify-between px-10 bg-white">
                    <div className="flex py-2 items-center">
                        <Image src={Logo} alt="logo image" width={150} />
                    </div>



                    <div className="bg-white-500 relative w-3/5">
                        <div className="text-black items-center py-2  h-full w-full justify-around flex">
                            <p>
                                Home
                            </p>
                            <p>
                                Tour
                            </p>
                            <p>
                                Activities
                            </p>
                            <p>
                                Hotels
                            </p>
                            <p>
                                Car Rental
                            </p>
                            <p>
                                Visa
                            </p>
                            <p>
                                Packages
                            </p>
                            <p>
                                Contact Us
                            </p>
                            <p className="bg-primary px-2 py-2 rounded shadow cursor-pointer text-white">
                                Make your trip
                            </p>
                        </div>
                        <div
                            style={{
                                borderTop: "25px solid white",
                                borderLeft: "12px solid transparent",
                                borderRight: "12px solid transparent",
                                bottom: "-20px"

                            }}
                            className="w-full absolute bg-transparent-500 items-center">
                        </div>
                    </div>

                    <div className="flex">
                        <div className="flex py-2 items-center ms-8">

                            <p className="flex items-center text-black mx-1">
                                < FaGlobeEurope className="mx-1" />
                                English
                            </p>
                            <p>
                                |
                            </p>
                            <p className="text-black mx-1">
                                USD
                            </p>

                        </div>

                    </div>
                </header>



                {children}</body>
        </html>
    );
}
