
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer/page";
<<<<<<< HEAD
import MobileNavbar from "@/components/Navbar/MobileNavbar";

const inter = Inter({ subsets: ["latin"] });

//export const metadata: Metadata = {
//    title: "Create Next App",
//    description: "Generated by create next app",
//};
=======
import Navbar from "@/components/Navbar/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
>>>>>>> 3e23430f86e42aca41a5981c6140d754e56996cd

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
<<<<<<< HEAD
    return (
        <html lang="en">
            <body className={inter.className}>
            <MobileNavbar />
=======
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
>>>>>>> 3e23430f86e42aca41a5981c6140d754e56996cd

        {children}

        <Footer />
      </body>
    </html>
  );
}
